name: 背景图更新  
  
on:    
  schedule:    
    - cron: '0 16 * * *' # 每天下午4点（UTC时间）运行一次  
  workflow_dispatch: # 支持手动触发  
  
jobs:    
  download-image:    
    runs-on: ubuntu-latest    
    steps:    
      - name: Checkout Repository    
        uses: actions/checkout@v2    
        with:    
          ref: main  
          token: ${{ secrets.PAT }} # 使用个人访问令牌
  
      - name: Download Image from Bing    
        run: |    
          # 从Bing获取图片信息  
          curl -s "https://bing.com/HPImageArchive.aspx?format=js&idx=0&n=1" > bing_image.json    
            
          # 从JSON中提取图片URL  
          IMAGE_URL=$(jq -r '.images[0].url' bing_image.json)    
            
          # 下载图片并保存为beijing-image.jpg  
          curl -s -o beijing-image.jpg "https://bing.com${IMAGE_URL}"    

      - name: List files in current directory
        run: ls -la

      - name: Commit and push image
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "MemoryCollection"
          git add --force beijing-image.jpg
          git commit --allow-empty -m "Add new image"
          git push
